export const INICIO_RESET_SEND = "INICIO_RESET_SEND";
export const ERRO_RESET_SEND = "ERRO_RESET_SEND";
export const SUCESSO_RESET_SEND = "SUCESSO_RESET_SEND";

export const INICIO_RESET_VERIFY = "INICIO_RESET_VERIFY";
export const ERRO_RESET_VERIFY = "ERRO_RESET_VERIFY";
export const SUCESSO_RESET_VERIFY = "SUCESSO_RESET_VERIFY";

export const SEM_JOGO = "SEM_JOGO"
export const BUSCA_PALAVRAS = "BUSCANDO_PALAVRAS"
export const PREPARAR = "PREPARANDO"
export const JOGAR = "JOGAR"
export const SALVAR_JOGO = "SALVAR_JOGO"
export const FINALIZAR = "FINALIZAR"
export const NOVA_PARTIDA = "NOVA_PARTIDA"


