export const SUCESSO_REGISTRO = "SUCESSO_REGISTRO";
export const ERRO_REGISTRO = "ERRO_REGISTRO";
export const INICIO_REGISTRO = "INICIO_REGISTRO";

export const SUCESSO_LOGIN = "SUCESSO_LOGIN";
export const ERRO_LOGIN = "ERRO_LOGIN";
export const INICIO_LOGIN = "INICIO_LOGIN";

export const INICIO_RESET_SEND = "INICIO_RESET_SEND";
export const ERRO_RESET_SEND = "ERRO_RESET_SEND";
export const SUCESSO_RESET_SEND = "SUCESSO_RESET_SEND";

export const INICIO_RESET_VERIFY = "INICIO_RESET_VERIFY";
export const ERRO_RESET_VERIFY = "ERRO_RESET_VERIFY";
export const SUCESSO_RESET_VERIFY = "SUCESSO_RESET_VERIFY";


